version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            tests:
               - unique
               - not_null
          - name: status
            tests:
               - accepted_values:
                    values: ['placed','shipped','completed','return_pending','returned']
  - name: stripe
    tables:
      - name: payment